import type { Metadata } from "next";
import "./globals.css";
import RecoilProvider from "./config/RecoilProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilProvider>
          <p>From Layout</p>
          {children}
        </RecoilProvider>
      </body>
    </html>
  );
}
